import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export async function generate(config) {
  const { projectName, typescript, tailwind, authUI, routerType = 'app' } = config;
  const ext = typescript ? 'tsx' : 'jsx';
  const configExt = typescript ? 'ts' : 'js';
  
  // Package.json
  const packageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      next: '^13.4.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0'
    },
    devDependencies: {}
  };
  
  if (tailwind) {
    packageJson.devDependencies = {
      ...packageJson.devDependencies,
      tailwindcss: '^3.3.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0'
    };
  }
  
  if (typescript) {
    packageJson.devDependencies = {
      ...packageJson.devDependencies,
      '@types/node': '^20.0.0',
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      typescript: '^5.0.0',
      '@typescript-eslint/parser': '^6.0.0',
      '@typescript-eslint/eslint-plugin': '^6.0.0'
    };
  }
  
  await fs.writeJson('package.json', packageJson, { spaces: 2 });
  
  // Next.js config
  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: ${routerType === 'app'}
  },
  images: {
    domains: ['zenuxs.in'],
  },
}

module.exports = nextConfig
`;
  await fs.writeFile('next.config.js', nextConfig);
  
  // TS Config
  if (typescript) {
    const tsConfig = `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
    await fs.writeFile('tsconfig.json', tsConfig);
  }
  
  // Directory structure
  if (routerType === 'app') {
    await generateAppRouter(config);
  } else {
    await generatePagesRouter(config);
  }
  
  // Tailwind setup
  if (tailwind) {
    await generateTailwindConfig(config);
  }
}

async function generateAppRouter(config) {
  const { projectName, typescript, tailwind, authUI } = config;
  const ext = typescript ? 'tsx' : 'jsx';
  
  await fs.ensureDir('app');
  await fs.ensureDir('app/zenuxs');
  await fs.ensureDir('app/api');
  await fs.ensureDir('components');
  await fs.ensureDir('lib');
  await fs.ensureDir('public');
  
  // Layout
  const layoutContent = `import './globals.css'
${typescript ? `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Zenuxs CLI',
}` : `export const metadata = {
  title: '${projectName}',
  description: 'Generated by Zenuxs CLI',
}`}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={${typescript ? 'inter.className' : '"min-h-screen bg-gray-50"'}}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}

function Navbar() {
  return (
    <nav className="bg-white shadow-lg">
      <div className="container mx-auto px-4">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <a href="/" className="text-xl font-bold text-gray-800">
              ${projectName}
            </a>
          </div>
          <div className="flex items-center space-x-4">
            <a href="/" className="text-gray-600 hover:text-gray-900">
              Home
            </a>
            <a href="/zenuxs" className="text-gray-600 hover:text-gray-900">
              Zenuxs
            </a>
            ${authUI ? `
            <a href="/login" className="text-gray-600 hover:text-gray-900">
              Login
            </a>
            <a href="/register" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Register
            </a>` : ''}
          </div>
        </div>
      </div>
    </nav>
  )
}

function Footer() {
  return (
    <footer className="bg-gray-800 text-white py-8 mt-auto">
      <div className="container mx-auto px-4">
        <div className="flex flex-col md:flex-row justify-between items-center">
          <div className="mb-4 md:mb-0">
            <h3 className="text-xl font-bold">${projectName}</h3>
            <p className="text-gray-400 mt-2">
              Built with Zenuxs CLI
            </p>
          </div>
          <div className="flex space-x-6">
            <a href="https://zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-gray-300 hover:text-white">
              Zenuxs
            </a>
            <a href="https://easy-mongoo.zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-gray-300 hover:text-white">
              Easy-Mongoo
            </a>
            <a href="https://hmax.zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-gray-300 hover:text-white">
              HMAX
            </a>
          </div>
        </div>
        <div className="mt-8 pt-8 border-t border-gray-700 text-center text-gray-400">
          <p>&copy; ${new Date().getFullYear()} ${projectName}. All rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}
`;
  await fs.writeFile(`app/layout.${ext}`, layoutContent);
  
  // Home page
  const pageContent = `export default function Home() {
  return (
    <main className="min-h-screen">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Welcome to ${config.projectName}
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            A Next.js application created with Zenuxs CLI
          </p>
          
          <div className="flex flex-wrap justify-center gap-4 mb-12">
            <a
              href="/zenuxs"
              className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
            >
              Visit Zenuxs Page
            </a>
            ${authUI ? `
            <a
              href="/login"
              className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition"
            >
              Login
            </a>
            <a
              href="/register"
              className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition"
            >
              Register
            </a>` : ''}
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-xl shadow-lg">
              <h3 className="text-2xl font-bold text-gray-800 mb-3">Zenuxs Accounts</h3>
              <p className="text-gray-600 mb-4">Manage your Zenuxs account and services</p>
              <a href="https://zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                zenuxs.in →
              </a>
            </div>
            
            <div className="bg-white p-6 rounded-xl shadow-lg">
              <h3 className="text-2xl font-bold text-gray-800 mb-3">Easy-Mongoo</h3>
              <p className="text-gray-600 mb-4">Ultra-simple MongoDB wrapper with all Mongoose features</p>
              <a href="https://easy-mongoo.zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                easy-mongoo.zenuxs.in →
              </a>
            </div>
            
            <div className="bg-white p-6 rounded-xl shadow-lg">
              <h3 className="text-2xl font-bold text-gray-800 mb-3">HMAX Security</h3>
              <p className="text-gray-600 mb-4">Advanced security for your applications</p>
              <a href="https://hmax.zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                hmax.zenuxs.in →
              </a>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
`;
  await fs.writeFile(`app/page.${ext}`, pageContent);
  
  // Zenuxs page
  const zenuxsPage = `export default function ZenuxsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-xl p-8">
          <div className="text-center mb-10">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">
              🚀 Project created using Zenuxs CLI
            </h1>
            <p className="text-gray-600 text-lg">
              Your Next.js application is ready to go!
            </p>
          </div>
          
          <div className="space-y-6">
            <div className="border-l-4 border-blue-500 pl-4 py-2">
              <h3 className="text-xl font-semibold text-gray-800 mb-2">📚 Documentation</h3>
              <ul className="space-y-2">
                <li>
                  <a href="https://zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                    • Zenuxs Accounts: https://zenuxs.in
                  </a>
                </li>
                <li>
                  <a href="https://easy-mongoo.zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                    • Easy-Mongoo Docs: https://easy-mongoo.zenuxs.in
                  </a>
                </li>
                <li>
                  <a href="https://hmax.zenuxs.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                    • HMAX Security: https://hmax.zenuxs.in
                  </a>
                </li>
              </ul>
            </div>
            
            <div className="border-l-4 border-green-500 pl-4 py-2">
              <h3 className="text-xl font-semibold text-gray-800 mb-2">⚡ Quick Start</h3>
              <div className="bg-gray-50 p-4 rounded-lg">
                <code className="text-sm text-gray-800 font-mono">
                  npm run dev
                </code>
              </div>
            </div>
            
            <div className="border-l-4 border-purple-500 pl-4 py-2">
              <h3 className="text-xl font-semibold text-gray-800 mb-2">✨ Features</h3>
              <ul className="space-y-2">
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-blue-500 rounded-full mr-2"></span>
                  Next.js ${config.typescript ? 'TypeScript' : 'JavaScript'}
                </li>
                <li className="flex items-center">
                  <span className="w-2 h-2 bg-blue-500 rounded-full mr-2"></span>
                  App Router
                </li>
                ${config.tailwind ? `<li className="flex items-center">
                  <span className="w-2 h-2 bg-blue-500 rounded-full mr-2"></span>
                  Tailwind CSS
                </li>` : ''}
                ${config.authUI ? `<li className="flex items-center">
                  <span className="w-2 h-2 bg-blue-500 rounded-full mr-2"></span>
                  Authentication UI
                </li>` : ''}
              </ul>
            </div>
          </div>
          
          <div className="mt-10 pt-8 border-t border-gray-200 text-center">
            <p className="text-gray-500">
              Built with ❤️ by <a href="https://zenuxs.in" className="text-blue-600 hover:underline">Zenuxs Team</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
`;
  await fs.writeFile(`app/zenuxs/page.${ext}`, zenuxsPage);
  
  // API route example
  const apiRoute = `export async function GET(request) {
  return new Response(JSON.stringify({
    message: 'Hello from ${config.projectName} API',
    timestamp: new Date().toISOString(),
    version: '1.0.0'
  }), {
    headers: {
      'content-type': 'application/json',
    },
  })
}
`;
  await fs.writeFile(`app/api/hello/route.${ext}`, apiRoute);
}

async function generatePagesRouter(config) {
  // Similar implementation for Pages Router
  // For brevity, I'll skip the detailed implementation
  const { projectName, typescript } = config;
  const ext = typescript ? 'tsx' : 'jsx';
  
  await fs.ensureDir('pages');
  await fs.ensureDir('pages/api');
  await fs.ensureDir('components');
  await fs.ensureDir('styles');
  await fs.ensureDir('public');
  
  const indexPage = `import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>${projectName}</title>
        <meta name="description" content="Generated by Zenuxs CLI" />
      </Head>
      
      <main>
        <h1>Welcome to ${projectName}</h1>
        <p>This is a Next.js application using Pages Router</p>
      </main>
    </div>
  )
}
`;
  
  await fs.writeFile(`pages/index.${ext}`, indexPage);
  
  const zenuxsPage = `export default function ZenuxsPage() {
  return (
    <div>
      <h1>Project created using Zenuxs CLI</h1>
      <p>Visit <a href="https://zenuxs.in">zenuxs.in</a></p>
    </div>
  )
}
`;
  
  await fs.writeFile(`pages/zenuxs.${ext}`, zenuxsPage);
  
  const apiRoute = `export default function handler(req, res) {
  res.status(200).json({
    message: 'Hello from ${config.projectName} API',
    timestamp: new Date().toISOString()
  })
}
`;
  
  await fs.writeFile(`pages/api/hello.${ext}`, apiRoute);
}

async function generateTailwindConfig(config) {
  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        }
      }
    },
  },
  plugins: [],
}
`;
  
  await fs.writeFile('tailwind.config.js', tailwindConfig);
  
  const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
  
  await fs.writeFile('postcss.config.js', postcssConfig);
  
  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`;
  
  await fs.writeFile('app/globals.css', globalsCss);
}