import fs from 'fs-extra';

export async function generateNextJS(config) {
  const { projectName, typescript = true, tailwind = true } = config;
  const ext = typescript ? 'tsx' : 'jsx';
  
  // Create package.json
  const packageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      next: '^13.4.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0'
    },
    devDependencies: {}
  };
  
  if (tailwind) {
    packageJson.devDependencies = {
      ...packageJson.devDependencies,
      tailwindcss: '^3.3.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0'
    };
  }
  
  if (typescript) {
    packageJson.devDependencies = {
      ...packageJson.devDependencies,
      '@types/node': '^20.0.0',
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      typescript: '^5.0.0'
    };
  }
  
  await fs.writeJson('package.json', packageJson, { spaces: 2 });
  
  // Create next.config.js
  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true
  }
}

module.exports = nextConfig
`;
  await fs.writeFile('next.config.js', nextConfig);
  
  // Create app directory structure
  await fs.ensureDir('app');
  await fs.ensureDir('app/zenuxs');
  await fs.ensureDir('app/styles');
  
  // Create layout with conditional styling
  let layoutContent;
  if (tailwind) {
    layoutContent = `import './globals.css'
${typescript ? `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Zenuxs CLI',
}` : `export const metadata = {
  title: '${projectName}',
  description: 'Generated by Zenuxs CLI',
}`}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className="${typescript ? 'inter.className' : ''}">
        {children}
      </body>
    </html>
  )
}
`;
  } else {
    layoutContent = `import './styles/globals.css'
${typescript ? `import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Zenuxs CLI',
}` : `export const metadata = {
  title: '${projectName}',
  description: 'Generated by Zenuxs CLI',
}`}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
`;
  }
  
  await fs.writeFile(`app/layout.${ext}`, layoutContent);
  
  // Create page with conditional styling
  let pageContent;
  if (tailwind) {
    pageContent = `import Link from 'next/link'

export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-6">Welcome to ${projectName}</h1>
        <p className="text-lg mb-8">
          A Next.js application created with Zenuxs CLI
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="p-6 bg-white rounded-xl shadow">
            <h3 className="text-xl font-bold mb-2">Zenuxs Accounts</h3>
            <a href="https://zenuxs.in" className="text-blue-600 hover:underline">
              zenuxs.in →
            </a>
          </div>
          
          <div className="p-6 bg-white rounded-xl shadow">
            <h3 className="text-xl font-bold mb-2">Easy-Mongoo</h3>
            <a href="https://easy-mongoo.zenuxs.in" className="text-blue-600 hover:underline">
              easy-mongoo.zenuxs.in →
            </a>
          </div>
          
          <div className="p-6 bg-white rounded-xl shadow">
            <h3 className="text-xl font-bold mb-2">HMAX Security</h3>
            <a href="https://hmax.zenuxs.in" className="text-blue-600 hover:underline">
              hmax.zenuxs.in →
            </a>
          </div>
        </div>
        
        <Link
          href="/zenuxs"
          className="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          Visit Zenuxs Page
        </Link>
      </div>
    </main>
  )
}
`;
  } else {
    pageContent = `import Link from 'next/link'
import './styles/Home.module.css'

export default function Home() {
  return (
    <main className="home-container">
      <div className="home-content">
        <h1 className="home-title">Welcome to ${projectName}</h1>
        <p className="home-subtitle">
          A Next.js application created with Zenuxs CLI
        </p>
        
        <div className="home-cards">
          <div className="card">
            <h3 className="card-title">Zenuxs Accounts</h3>
            <a href="https://zenuxs.in" className="card-link">
              zenuxs.in →
            </a>
          </div>
          
          <div className="card">
            <h3 className="card-title">Easy-Mongoo</h3>
            <a href="https://easy-mongoo.zenuxs.in" className="card-link">
              easy-mongoo.zenuxs.in →
            </a>
          </div>
          
          <div className="card">
            <h3 className="card-title">HMAX Security</h3>
            <a href="https://hmax.zenuxs.in" className="card-link">
              hmax.zenuxs.in →
            </a>
          </div>
        </div>
        
        <Link
          href="/zenuxs"
          className="btn btn-primary"
        >
          Visit Zenuxs Page
        </Link>
      </div>
    </main>
  )
}
`;
    
    // Create CSS module for Home page
    const homeCss = `.home-container {
  min-height: 100vh;
  padding: 2rem;
  background-color: #f9fafb;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
}

.home-content {
  max-width: 64rem;
  margin: 0 auto;
}

.home-title {
  font-size: 2.25rem;
  font-weight: bold;
  margin-bottom: 1.5rem;
  color: #1a202c;
}

.home-subtitle {
  font-size: 1.125rem;
  margin-bottom: 2rem;
  color: #4a5568;
}

.home-cards {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-bottom: 2rem;
}

@media (min-width: 768px) {
  .home-cards {
    grid-template-columns: repeat(3, 1fr);
  }
}

.card {
  background: white;
  padding: 1.5rem;
  border-radius: 0.75rem;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
}

.card-title {
  font-size: 1.25rem;
  font-weight: bold;
  margin-bottom: 0.5rem;
}

.card-link {
  color: #2563eb;
  text-decoration: none;
}

.card-link:hover {
  text-decoration: underline;
}

.btn {
  display: inline-block;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  text-decoration: none;
  font-weight: 500;
  font-size: 1rem;
  border: none;
  cursor: pointer;
  transition: background-color 0.2s;
}

.btn-primary {
  background-color: #2563eb;
  color: white;
}

.btn-primary:hover {
  background-color: #1d4ed8;
}
`;
    
    await fs.writeFile('app/styles/Home.module.css', homeCss);
  }
  
  await fs.writeFile(`app/page.${ext}`, pageContent);
  
  // Create zenuxs page with conditional styling
  let zenuxsPage;
  if (tailwind) {
    zenuxsPage = `export default function ZenuxsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 p-8">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-xl p-8">
        <h1 className="text-4xl font-bold text-center mb-8">
          Project created using Zenuxs CLI
        </h1>
        
        <div className="space-y-6">
          <div>
            <h2 className="text-2xl font-semibold mb-4">Useful Links</h2>
            <ul className="space-y-2">
              <li>
                <a href="https://zenuxs.in" className="text-blue-600 hover:underline">
                  • Zenuxs Accounts: https://zenuxs.in
                </a>
              </li>
              <li>
                <a href="https://easy-mongoo.zenuxs.in" className="text-blue-600 hover:underline">
                  • Easy-Mongoo Docs: https://easy-mongoo.zenuxs.in
                </a>
              </li>
              <li>
                <a href="https://hmax.zenuxs.in" className="text-blue-600 hover:underline">
                  • HMAX Security: https://hmax.zenuxs.in
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
`;
  } else {
    zenuxsPage = `import './styles/ZenuxsPage.module.css'

export default function ZenuxsPage() {
  return (
    <div className="zenuxs-container">
      <div className="zenuxs-content">
        <h1 className="zenuxs-title">
          Project created using Zenuxs CLI
        </h1>
        
        <div className="zenuxs-info">
          <div>
            <h2 className="zenuxs-subtitle">Useful Links</h2>
            <ul className="zenuxs-links">
              <li>
                <a href="https://zenuxs.in" className="zenuxs-link">
                  • Zenuxs Accounts: https://zenuxs.in
                </a>
              </li>
              <li>
                <a href="https://easy-mongoo.zenuxs.in" className="zenuxs-link">
                  • Easy-Mongoo Docs: https://easy-mongoo.zenuxs.in
                </a>
              </li>
              <li>
                <a href="https://hmax.zenuxs.in" className="zenuxs-link">
                  • HMAX Security: https://hmax.zenuxs.in
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
`;
    
    // Create CSS module for Zenuxs page
    const zenuxsCss = `.zenuxs-container {
  min-height: 100vh;
  padding: 2rem;
  background: linear-gradient(135deg, #eff6ff 0%, #f5f3ff 100%);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
}

.zenuxs-content {
  max-width: 64rem;
  margin: 0 auto;
  background: white;
  border-radius: 1rem;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
  padding: 2rem;
}

.zenuxs-title {
  font-size: 2.25rem;
  font-weight: bold;
  text-align: center;
  margin-bottom: 2rem;
  color: #1a202c;
}

.zenuxs-info {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.zenuxs-subtitle {
  font-size: 1.5rem;
  font-weight: 600;
  margin-bottom: 1rem;
  color: #2d3748;
}

.zenuxs-links {
  list-style: none;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.zenuxs-link {
  color: #2563eb;
  text-decoration: none;
  font-size: 1.125rem;
}

.zenuxs-link:hover {
  text-decoration: underline;
}
`;
    
    await fs.writeFile('app/styles/ZenuxsPage.module.css', zenuxsCss);
  }
  
  await fs.writeFile(`app/zenuxs/page.${ext}`, zenuxsPage);
  
  // Create tailwind config if needed
  if (tailwind) {
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
    await fs.writeFile('tailwind.config.js', tailwindConfig);
    
    const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
    await fs.writeFile('postcss.config.js', postcssConfig);
    
    const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}
`;
    await fs.writeFile('app/globals.css', globalsCss);
  } else {
    // Create basic globals.css for non-Tailwind version
    const globalsCss = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

a {
  color: inherit;
  text-decoration: none;
}
`;
    
    await fs.writeFile('app/styles/globals.css', globalsCss);
  }
}   